# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test matrix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox test matrix
      run: |
        tox

    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pipenv
    #     pipenv install --dev --ignore-pipfile
    # - name: Run tests
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     pipenv run pytest -v
